# Generated by Django 3.2.5 on 2023-01-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizexam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizexam'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'quiz_exam')},
        ),
        migrations.AlterUniqueTogether(
            name='quizexam',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('name', 'quiz_exam')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'name', 'isAnswer')},
        ),
    ]
